package industrialmd

import (
	coremd "github.com/readmedotmd/style.md/core.md"
)

var theme = coremd.Themed{ClassMap: coremd.ClassMap{
	// Button
	Btn:        ClassBtn,
	BtnPrimary: ClassBtnPrimary,
	BtnDanger:  ClassBtnDanger,
	BtnSmall:   ClassBtnSmall,
	BtnToolbar: ClassBtnToolbar,

	// Layout
	AppShell:        ClassAppShell,
	AppShellBody:    ClassAppShellBody,
	AppShellMain:    ClassAppShellMain,
	Navbar:          ClassNavbar,
	Sidebar:         ClassSidebar,
	SidebarOpen:     ClassSidebarOpen,
	SidebarHeader:   ClassSidebarHeader,
	Panel:           ClassPanel,
	PanelExpanded:   ClassPanelExpanded,
	ModalBackdrop:   ClassModalBackdrop,
	Modal:           ClassModal,
	ModalBody:       ClassModalBody,
	ModalFooter:     ClassModalFooter,
	DragHandle:      ClassDragHandle,
	DashboardLayout: ClassDashboardLayout,
	SidebarCol:      ClassSidebarCol,
	SidebarColOpen:  ClassSidebarColOpen,
	SidebarOverlay:  ClassSidebarOverlay,
	CenterCol:       ClassCenterCol,
	ChatArea:        ClassChatArea,
	ChatHeaderCls:   ClassChatHeader,
	MsgList:         ClassMsgList,
	ChatInputArea:   ClassChatInputArea,
	ChatInputRow:    ClassChatInputRow,
	ChatInputWrap:   ClassChatInputWrap,
	ChatInputWrapEx: ClassChatInputWrapEx,

	// Navigation
	NavLink:       ClassNavLink,
	NavLinkActive: ClassNavLinkActive,
	TabBar:        ClassTabBar,
	BottomTabBar:  ClassBottomTabBar,
	ChatBackBtn:   ClassChatBackBtn,
	HamburgerBtn:  ClassHamburgerBtn,
	ChatToolbar:   ClassChatToolbar,
	ToolbarBtn:    ClassToolbarBtn,
	ToolbarBtnDgr: ClassToolbarBtnDgr,

	// Data Display
	Message:            ClassMessage,
	MessageUser:        ClassMessageUser,
	MessageAssistant:   ClassMessageAssistant,
	MessageStreaming:   ClassMessageStreaming,
	Thinking:           ClassThinking,
	ThinkingCollapsib:  ClassThinkingCollapsib,
	ToolBadge:          ClassToolBadge,
	QuestionPrompt:     ClassQuestionPrompt,
	StatusBadge:        ClassStatusBadge,
	StatusBadgePrefix:  "status-badge--",
	StatusDot:          ClassStatusDot,
	StatusDotPrefix:    "status-dot--",
	LabelBadge:         ClassLabelBadge,
	UsageBadge:         ClassUsageBadge,
	DiffViewer:         ClassDiffViewer,
	DataTable:          ClassDataTable,
	EmptyState:         ClassEmptyState,
	ClusterStats:       ClassClusterStats,
	MessageContent:     ClassMessageContent,
	MessageContentUser: ClassMessageContentUser,
	WorkingIndicator:   ClassWorkingIndicator,
	ChatStatusBadge:    ClassChatStatusBadge,
	ThinkingHistory:    ClassThinkingHistory,
	ChatError:          ClassChatError,
	AcceptPlanBar:      ClassAcceptPlanBar,

	// List
	ConversationItem:       ClassConversationItem,
	ConversationItemActive: ClassConversationItemActive,
	InstanceCard:           ClassInstanceCard,
	InstanceCardActive:     ClassInstanceCardActive,
	ServiceRow:             ClassServiceRow,
	RunnerRow:              ClassRunnerRow,
	FileTree:               ClassFileTree,

	// Form
	FormGroup:       ClassFormGroup,
	TextInput:       ClassTextInput,
	TextInputError:  ClassTextInputError,
	Textarea:        ClassTextarea,
	TextareaAutoGrw: ClassTextareaAutoGrw,
	TextareaFixed:   ClassTextareaFixed,
	Select:          ClassSelect,
	Checkbox:        ClassCheckbox,
	FeatureRow:      ClassFeatureRow,
	VariableRow:     ClassVariableRow,
	ErrorMessage:    ClassErrorMessage,
	SuccessMessage:  ClassSuccessMessage,

	// Input
	ChatInput:       ClassChatInput,
	Autocomplete:    ClassAutocomplete,
	MessageQueue:    ClassMessageQueue,
	SearchInput:     ClassSearchInput,
	PastePreview:    ClassPastePreview,
	ExpandBtn:       ClassExpandBtn,
	AttachBtn:       ClassAttachBtn,
	SendBtn:         ClassSendBtn,
	CancelBtn:       ClassCancelBtn,
	ModeBtn:         ClassModeBtn,
	MsgQueueBar:     ClassMsgQueueBar,
	QueuedItem:      ClassQueuedItem,
	AutocompleteHdr: ClassAutocompleteHdr,

	// Overlay
	SearchOverlay:       ClassSearchOverlay,
	ContextMenu:         ClassContextMenu,
	BottomSheet:         ClassBottomSheet,
	SearchCard:          ClassSearchCard,
	SearchResult:        ClassSearchResult,
	SearchResultContent: ClassSearchResultContent,
	SearchSnippet:       ClassSearchSnippet,

	// Panel compositions
	SkillCard:         ClassSkillCard,
	TerminalPanel:     ClassTerminalPanel,
	GitPanelCls:       ClassGitPanel,
	GitSectionHdr:     ClassGitSectionHdr,
	GitFileList:       ClassGitFileList,
	GitFile:           ClassGitFile,
	GitFileSelected:   ClassGitFileSelected,
	GitCommitArea:     ClassGitCommitArea,
	DiffCommentBtn:    ClassDiffCommentBtn,
	DiffInlineComment: ClassDiffInlineComment,
	SvcActionBtn:      ClassSvcActionBtn,
	RunnerEmpty:       ClassRunnerEmpty,

	// Page
	LoginPage:           ClassLoginPage,
	SettingsPage:        ClassSettingsPage,
	SettingsCardFull:    ClassSettingsCardFull,
	SettingsSection:     ClassSettingsSection,
	SettingsSubsection:  ClassSettingsSubsection,
	SettingsForm:        ClassSettingsForm,
	SettingsFormActions:  ClassSettingsFormActions,
	SettingsFormHelp:    ClassSettingsFormHelp,
	SettingsCodeInput:   ClassSettingsCodeInput,
	SettingsEnvRow:      ClassSettingsEnvRow,
	SettingsFieldError:  ClassSettingsFieldError,
	SettingsSchemaTable: ClassSettingsSchemaTable,
	AdminPage:           ClassAdminPage,
	ClusterPageCls:      ClassClusterPage,
	ClusterSummaryCard:  ClassClusterSummaryCard,
	ClusterSummaryRow:   ClassClusterSummaryRow,

	// Utility
	Spinner:      ClassSpinner,
	SpinnerSmall: ClassSpinnerSmall,
	SpinnerLarge: ClassSpinnerLarge,
	Icon:         ClassIcon,
	AppShellFull: ClassAppShellFull,
}}
